services:
  node-a-1:
    build: .
    command: ["node", "node/server.js"]
    environment:
      PORT: 4001
      NODE_ID: node-a-1
      NODE_DATASET: shard-a
      NODE_SHARD_ID: shard-a
      NODE_REPLICA_GROUP: replica-a
      COORDINATOR_URL: http://coordinator:4000
      NODE_PUBLIC_URL: http://node-a-1:4001
    ports:
      - "4001:4001"

  node-a-2:
    build: .
    command: ["node", "node/server.js"]
    environment:
      PORT: 4002
      NODE_ID: node-a-2
      NODE_DATASET: shard-a
      NODE_SHARD_ID: shard-a
      NODE_REPLICA_GROUP: replica-a
      COORDINATOR_URL: http://coordinator:4000
      NODE_PUBLIC_URL: http://node-a-2:4002
    ports:
      - "4002:4002"

  node-b-1:
    build: .
    command: ["node", "node/server.js"]
    environment:
      PORT: 4003
      NODE_ID: node-b-1
      NODE_DATASET: shard-b
      NODE_SHARD_ID: shard-b
      NODE_REPLICA_GROUP: replica-b
      COORDINATOR_URL: http://coordinator:4000
      NODE_PUBLIC_URL: http://node-b-1:4003
    ports:
      - "4003:4003"

  node-b-2:
    build: .
    command: ["node", "node/server.js"]
    environment:
      PORT: 4004
      NODE_ID: node-b-2
      NODE_DATASET: shard-b
      NODE_SHARD_ID: shard-b
      NODE_REPLICA_GROUP: replica-b
      COORDINATOR_URL: http://coordinator:4000
      NODE_PUBLIC_URL: http://node-b-2:4004
    ports:
      - "4004:4004"

  aggregator:
    build: .
    command: ["node", "aggregator/server.js"]
    environment:
      PORT: 4005
    ports:
      - "4005:4005"

  coordinator:
    build: .
    command: ["node", "coordinator/server.js"]
    environment:
      PORT: 4000
      AGGREGATOR_URL: http://aggregator:4005
    depends_on:
      - node-a-1
      - node-a-2
      - node-b-1
      - node-b-2
      - aggregator
    ports:
      - "4000:4000"

  client:
    build: .
    command: ["node", "client/server.js"]
    environment:
      PORT: 3000
      COORDINATOR_URL: http://coordinator:4000
    depends_on:
      - coordinator
    ports:
      - "3000:3000"
